EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\nova', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\nova', @rolename = N'serveradmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\dcrowley', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'securityadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'serveradmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'setupadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'processadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'diskadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'dbcreator'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Domain Admins', @rolename = N'bulkadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\amcphee_admin', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\sfearon', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\mlasater', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHREEU\mbennett', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHREEU\fmcmahon', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'Nova', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\lmurdick', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHREEU\dcasey', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\cproiete', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\svc_symantec', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\dcasey', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\jlatour', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\kterceira', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\amatia', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\wmehra', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'securityadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'serveradmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'setupadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'processadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'diskadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'dbcreator'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\twilborn', @rolename = N'bulkadmin'
EXEC master..sp_addsrvrolemember @loginame = N'twilborn', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'amatia', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\spasham', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'spasham', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\aalley', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\Mgrotheer', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\ydu', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\nsharma', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ydu', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'nsharma', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\gsmith', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'securityadmin'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'serveradmin'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'setupadmin'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'processadmin'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'diskadmin'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'dbcreator'
EXEC master..sp_addsrvrolemember @loginame = N'mgrotheer', @rolename = N'bulkadmin'
EXEC master..sp_addsrvrolemember @loginame = N'bpadodara', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\bpadodara', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\psathi', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\ArchAnalyticsSSISPro', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'wmehra', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'ARCHRE\rfrigola', @rolename = N'sysadmin'
EXEC master..sp_addsrvrolemember @loginame = N'test', @rolename = N'sysadmin'
