[sa]  
[##MS_SQLResourceSigningCertificate##]  
[##MS_SQLReplicationSigningCertificate##]  
[##MS_SQLAuthenticatorCertificate##]  
[##MS_PolicySigningCertificate##]  
[##MS_SmoExtendedSigningCertificate##]  
[##MS_PolicyTsqlExecutionLogin##]  
[NT SERVICE\SQLWriter]  
[NT SERVICE\Winmgmt]  
[NT Service\MSSQLSERVER]  
[NT AUTHORITY\SYSTEM]  
[NT SERVICE\SQLSERVERAGENT]  
[##MS_SQLEnableSystemAssemblyLoadingUser##]  
[##MS_SSISServerCleanupJobLogin##]  
[##MS_PolicyEventProcessingLogin##]  
[##MS_AgentSigningCertificate##]  
[bpadodara]  
[ARCHRE\bpadodara]  
[nsharma]  
[wmehra]  
[ARCHRE\nsharma]  
[ARCHRE\aalley]  
[ARCHRE\amcphee_admin]  
[ARCHRE\MI_Service]  
[ARCHRE\Domain Admins]  
[ARCHRE\MIDatabase Users]  
[reportinguser]  
[ARCHRE\svc_symantec]  
[ARCHRE\jlatour]  
[archmi_sqlclr]  
[microsoft_sqlclr_publickeytoken_b03f5f7f11d50a3a]  
[ARCHRE\wmehra]  
[dev_read_only]  
[sqlsourcecontrolapp]  
[app_read_only]  
[ARCHRE\gsmith]  
[ARCHRE\psathi]  
[ARCHRE\ArchAnalyticsSSISPro]  
[ARCHRE\rfrigola]  
