ALTER LOGIN [ARCHRE\dcrowley] DISABLE 
Go
ALTER LOGIN [ARCHRE\nova] DISABLE 
Go

ALTER LOGIN [ARCHRE\sfearon] DISABLE 
Go
ALTER LOGIN [ARCHRE\mlasater] DISABLE 
Go
ALTER LOGIN [ARCHREEU\mbennett] DISABLE 
Go
ALTER LOGIN [ARCHREEU\fmcmahon] DISABLE 
Go
ALTER LOGIN [Nova] DISABLE 
Go

ALTER LOGIN [ARCHRE\lmurdick] DISABLE 
Go
ALTER LOGIN [ARCHREEU\dcasey] DISABLE 
Go
ALTER LOGIN [ARCHRE\cproiete] DISABLE 
Go


ALTER LOGIN [ARCHRE\dcasey] DISABLE 
Go

ALTER LOGIN [ARCHRE\kterceira] DISABLE 
Go
ALTER LOGIN [ARCHRE\amatia] DISABLE 
Go
ALTER LOGIN [ARCHRE\swati] DISABLE 
Go


ALTER LOGIN [ARCHRE\twilborn] DISABLE 
Go

ALTER LOGIN [twilborn] DISABLE 
Go
ALTER LOGIN [amatia] DISABLE 
Go
ALTER LOGIN [ARCHRE\spasham] DISABLE 
Go
ALTER LOGIN [spasham] DISABLE 
Go

ALTER LOGIN [ARCHRE\bgali] DISABLE 
Go

ALTER LOGIN [ARCHRE\Bphilip] DISABLE 
Go
ALTER LOGIN [ARCHRE\Mgrotheer] DISABLE 
Go
ALTER LOGIN [ARCHRE\ydu] DISABLE 
Go

ALTER LOGIN [ydu] DISABLE 
Go


ALTER LOGIN [mgrotheer] DISABLE 
Go

ALTER LOGIN [ARCHRE\smason] DISABLE 
Go
ALTER LOGIN [smason] DISABLE 
Go



ALTER LOGIN [test] DISABLE 
Go